/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capenta.problem3;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import com.capenta.problem3.App;

class AppTest {
    @Test
    void appHasAGreeting() {
    	App.main(new String[0]);
    }
}
