/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.mellbourn.problem3;

import org.junit.jupiter.api.Test;

import net.mellbourn.problem3.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void canRunMain() {
    	App.main(new String[0]);
    }
}
